// AUTO-GENERATED by tests/data/generate_fixtures.py. Do not edit by hand.
//
// Reference similarity_score(test_k, class_j) computed by a pure-NumPy
// reimplementation of Eqs. 1-3 with the same solver tolerances as
// similarity_score's C++ defaults. The C++ integration test compares its
// own results to these values to cross-validate the implementation.

#pragma once

#include "fixtures_data.hpp"

namespace mqces::test_fixtures {

// Row-major (test_k × class_j).
extern const double expected_scores[N_CLASSES * N_CLASSES];

}  // namespace mqces::test_fixtures
