// AUTO-GENERATED by tests/data/generate_fixtures.py. Do not edit by hand.
//
// Synthetic 19-class burnup-style fixture for mqces integration tests.

#pragma once

namespace mqces::test_fixtures {

inline constexpr int N_CLASSES   = 19;
inline constexpr int N_SPECIMENS = 50;
inline constexpr int N_FEATURES  = 9;

extern const char*  class_names[N_CLASSES];
extern const double feature_weights[N_FEATURES];
extern const double class_data[N_CLASSES * N_SPECIMENS * N_FEATURES];
extern const double test_data [N_CLASSES * N_SPECIMENS * N_FEATURES];

}  // namespace mqces::test_fixtures
